---
# Per environment values which override defaults in hmpps-prisoner-pay-orchestrator-api/values.yaml

generic-service:
  ingress:
    host: prisoner-pay-orchestrator-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_PRISONER_PAY_API: "https://prisoner-pay-api.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search.prison.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-activities-management-prod
